theme: jekyll-theme-tactile
title: AdGen: An auto-generator for ads with never-seen-before humans
description: Detailed explanation of the AdGen project (CSCI-566 at University of Southern California)
